### ISSUE TITLE
Ask for collaboration

### ISSUE THREAD

**Issue by Gk0Wk** [SmilyOrg/tw5-monaco#7]
Hello, I am the author of [TW5-CodeMirror-Enhanced](https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced). First of all, thank you very much for the work you've done!

Secondly, I've always wanted to try to bring Monaco to TiddlyWiki, because during the development process, I gradually found that CodeMirror was difficult to adapt and required some extra work; at the same time, CodeMirror didn't provide a good syntax parser generation tool, which caused many features that required parsing syntax to work to be delayed. This resulted in many features that require parsing to work being delayed.

I am also a heavy user of VSCode, so I approve of Monaco, and I am happy that someone has the same idea as me and put it into practice. So I'm going to abandon my previous CME project and work with you on this one.

Can we have further discussions?

**Comment by SmilyOrg** [comment]
Hey @Gk0Wk!

That enhanced version of CodeMirror indeed looks like it has some of the very same goals, so nice work there! I've always felt that CodeMirror integration was a great effort, but the editor itself felt outdated in the context of VSCode / Monaco, so I can relate to your points :)

I would be happy to collaborate with you on this plugin! We can build collaboration guidelines as we go along. For now I've opened up Discussions for possibly easier conversations, the issues represent some of the things I was thinking of doing - I've assigned myself to the one palette issue I'm working on right now, but we can create a Kanban if needed later.

Let me know if you need some help getting started / finding tasks to work on or anything else.

**Comment by Gk0Wk** [comment]
Great! Then I will discuss further topics in Discussion.

Have a nice day!
